### PR TITLE
Removed references of day blooms

### PR DESCRIPTION
**Pull request by eccentricayman**

### CODE REVIEW

**Comment by williewillus** [comment]
Might as well do all the lang files if you're going to do this :P

**Comment by eccentricayman** [comment]
Working on it whoops

**Comment by eccentricayman** [comment]
Hydrangeas are going to be the only passives at this point, correct?

**Comment by eccentricayman** [comment]
Yeah this was a mistake, I was gonna do it all at once; I'll just close this pr

**Comment by Vazkii** [comment]
This is not what I'm going for as I do want to redo a bit of the earlygame progression. I appreciate it, but I'd rather people refrain from doing changes now until I have something properly set up.

**Pull request closed without merging**
